version: '3.3'
services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn wishlist.wsgi:application --bind 0.0.0.0:8000 
    #ports:
    #  - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/wishlist
      - ./static:/home/app/web/static
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./static:/home/app/web/static
